name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ secrets.ozkioz }}/devops-app .

      - name: Login to DockerHub
        run: echo ${{ secrets.lolfacelol1 }} | docker login -u ${{ secrets.ozkioz }} --password-stdin

      - name: Push image to DockerHub
        run: docker push ${{ secrets.ozkioz }}/devops-app